# Original https://github.com/mozilla/grcov/blob/master/.pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: check-json
    -   id: check-vcs-permalinks
    -   id: trailing-whitespace
        exclude: ^test/
    -   id: mixed-line-ending
        exclude: ^test/
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
    -   id: markdownlint
-   repo: https://github.com/DevinR528/cargo-sort
    rev: v1.0.7
    hooks:
    -   id: cargo-sort

default_language_version:
    python: python3
